[phases.setup]
nixPkgs = ["nodejs_22", "npm-10_x", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "node scripts/build-prisma-schema.js",
  "npx prisma generate",
  "npx nest build"
]

[start]
cmd = "npm run prisma:build && npx prisma migrate deploy && npm run start:prod"
